### ISSUE TITLE
BUG: "One row per layer group" not working correctly

### ISSUE THREAD

**Issue by nerudaj** [malteehrlen/tilemancer#3]
(Using Gimp 2.10.24)

Consider following grouping:

![image](https://user-images.githubusercontent.com/21182291/180323890-7329b517-e2d5-4f6f-a6cf-20724bb5ab35.png)

I would expect that when using option "One row per layer group" it would produce square tileset with first row being yellow and green and second being blue and red. Instead, I only get the first row, not the second one (still, it is in reverse order, but I don't really mind that).

![image](https://user-images.githubusercontent.com/21182291/180324661-632fc9df-05ef-48db-a4f3-101224821402.png)

Plus: Using "Square" option doesn't make any sense when groups are involved - error in that case might be nice.

**Comment by malteehrlen** [comment]
Hi @nerudaj thank you for the bug report! I cant promise when, but ill have a look at fixing this

**Comment by nerudaj** [comment]
~~I suspect line 10 to be the culprit, as it hardcodes parameter `row` of `sheeterize-group` function to zero, however it's been years when I last coded in LISP, so I have hard time parsing the code.~~

Okay so I think the problem is the following - you get list of layers `[ L1, L2, ... ]`, then you iterate over that list with `row = 0`. For each item in that list you ask whether it is a group or normal layer. If it is a layer, you draw it, if it is a group, you recurse, with `row+1`. Which means all layers in my example will be rendered with `row = 1`.

So naive fix would be to set row to index of currently iterated item (+1), but that would only work if there are no nested groups.

The true fix is to flatten all nested groups into single list and then ideally recurse/iterate over each item normally:

* Group1
    * Group 1_1
        * L1
        * L2
    * Group 1_2
        * L3
* Group2
    * L4
    * L5     

Should become:

* Group1_1
    * L1
    * L2
* Group1_2
    * L3
* Group2
    * L4
    * L5     

Now it's time for me to google how to flatten those lists 😂

**EDIT:**

Here's the "naive approach" fix, complete with tile spacing:

```
(define (sheeterize-group image item-vect framesize row spacing)
  (let* ((width (car (gimp-image-width image)))
    (height (car (gimp-image-height image)))
    (cols (vector-length item-vect))) 
    (do ((i 0 (+ i 1))) ((= i cols)) 
      (let* ((current-item (vector-ref item-vect i))
        (xpos (* (- cols 1 i) (+ spacing (car framesize)))))
        (if 
            (= 0 (car (gimp-item-is-group current-item)))
            ; if this particular item is not group, print it on current row
            (gimp-layer-translate current-item xpos (* row (+ spacing (cdr framesize))))
            ; if it is group, recurse and use current item index as row index
            (sheeterize-group image (cadr (gimp-item-get-children current-item)) framesize i spacing))))))
```

I really don't know how to properly sanitize those lists, but this at least fixes my original issue. I'll leave the decision of integrating this one up to you.
