### ISSUE TITLE
Feature request: Tile spacing

### ISSUE THREAD

**Issue by nerudaj** [malteehrlen/tilemancer#4]
It would be nice if there was an option for adding some space between tiles that would be filled with transparency.

![image](https://user-images.githubusercontent.com/21182291/180326170-6be81a46-65ac-46c2-a4b9-7027084c2cb0.png)

**WHY:**
Rendering libraries often have problems with color bleeding when tiles are next to each other.

**Comment by malteehrlen** [comment]
This also seems reasonable, I will have  look
